salt-extensions/saltext-vault

src/saltext/saltext_vault/runners/vault.py

Moving private functions calls to utils by exposing get_cache_backend function to be used by the runner.
This will also fix tests where `clear_cache` runner is used (`test_impersonating_master_does_not_override_issue_param_overrides`).

fixing clear_cache runner

---

.github/workflows/docs-action.yml
.github/workflows/test-action.yml

Migrate from `set-output` to environment files - `set-output` has been deprecated https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This solves the warnings logged by CI.
Also updates setup-vault and setup-python (in docs build) actions

Fix GH actions warnings

---

.github/workflows/docs-action.yml
.github/workflows/test-action.yml

* Previously, only pre-commit was required to report success, but all our jobs should be required.
* Rerunning failed jobs resulted in an exit status failure bc of missing artifact named `exitstatus` (https://github.com/salt-extensions/saltext-vault/actions/runs/7160303700/job/19494800090).

Always upload exit status

---

docs/all.rst
docs/ref/utils/index.rst
docs/ref/utils/saltext.vault.utils.versions.rst
src/saltext/vault/modules/vault.py
src/saltext/vault/pillar/vault.py
src/saltext/vault/runners/vault.py
src/saltext/vault/sdb/vault.py
src/saltext/vault/states/vault.py
src/saltext/vault/utils/vault/__init__.py
src/saltext/vault/utils/vault/api.py
src/saltext/vault/utils/vault/auth.py
src/saltext/vault/utils/vault/cache.py
src/saltext/vault/utils/vault/factory.py
src/saltext/vault/utils/vault/kv.py
src/saltext/vault/utils/vault/leases.py
src/saltext/vault/utils/versions.py
tests/unit/runners/vault/test_token_auth_deprecated.py
tests/unit/utils/vault/test_client.py
tests/unit/utils/vault/test_kv.py

Some minor fixes/improvements that were not part of the PR and further cleanup.
Additionally:
* Remove `versionadded`/`versionchanged` from previous Salt releases (irrelevant for a new project)
* Change `versionadded`/`versionchanged` from `3007.0` to `1.0.0` to highlight the differences vs Salt core
* Change calls to `salt.utils.versions.warn_until` to a local analog since we're independent from Salt releases now.
* Ensure we have a path to migrate from some currently broken (but backwards-compatible) defaults to more sensible ones (SDB `patch` behavior false -> true and `vault.list_secrets` returning the list instead of a single-key dict `{keys: [secret/keys, we/actually/asked/for]}`
After this, I think the following still needs to happen before a release:
* ~~I remember there was an …

Missing fixes, docs and deprecations rework

---

changelog/10.fixed.md
changelog/11.fixed.md
changelog/12.fixed.md
changelog/13.fixed.md
changelog/14.fixed.md
changelog/15.fixed.md
changelog/16.added.md
changelog/17.added.md
changelog/18.added.md
changelog/19.added.md
changelog/20.added.md
changelog/21.added.md
changelog/22.fixed.md
changelog/23.added.md

Based on https://github.com/salt-extensions/saltext-vault/pull/9
Ensures we have some kind of changelog vs the Salt core modules.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/10
Fixes: https://github.com/salt-extensions/saltext-vault/issues/11
Fixes: https://github.com/salt-extensions/saltext-vault/issues/12
Fixes: https://github.com/salt-extensions/saltext-vault/issues/13
Fixes: https://github.com/salt-extensions/saltext-vault/issues/14
Fixes: https://github.com/salt-extensions/saltext-vault/issues/15
Fixes: https://github.com/salt-extensions/saltext-vault/issues/16
Fixes: https://github.com/salt-extensions/saltext-vault/issues/17
Fixes: https://github.com/salt-extensions/saltext-vault/issues/18
Fixes: https://github.com/salt-extensions/saltext-vault/issues/19
Fixes: …

Add changelog news fragments from base PR

---

changelog/26.added.md
src/saltext/vault/modules/vault.py
src/saltext/vault/utils/vault/helpers.py
tests/unit/utils/vault/test_helpers.py

Adds support for using dict keys in patterns.
Example pillar:
```yaml
roles:
web:
some: config
mail:
other: stuff
```
Example pattern:
```yaml
vault:
policies:
assign:
- salt_minion
- 'salt_role_{pillar[roles]}'
```
Example output:
```yaml
- salt_minion
- salt_role_web
- salt_role_mail
```
Fixes: https://github.com/salt-extensions/saltext-vault/issues/26
Renders the whole dictionary as a single policy
Renders dictionary keys like lists
Yes

Support dict keys in patterns

---

changelog/30.changed.md
changelog/30.deprecated.md
docs/topics/migration_from_core.md
src/saltext/vault/pillar/vault.py
tests/integration/runners/test_vault.py
tests/unit/pillar/test_vault.py

(Based on https://github.com/salt-extensions/saltext-vault/pull/28)
This PR updates the pillar module to just ask for the path instead of the mandatory `path=` prefix to a less than ideal named parameter named `conf`, which is less confusing.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/30
```yaml
- ext_pillar:
- vault: path=foo/bar
- vault:
conf: path=foo/bar
```
```yaml
- ext_pillar:
- vault: foo/bar
- vault:
path: foo/bar
```
Yes

Deprecate nonsensical pillar configuration style

---

changelog/34.fixed.md
src/saltext/vault/utils/vault/client.py

I might be mistaken, but I think the unwrap request is missing the verify option.
Users are as a result unable to use unwrap with a custom verify setting.
I can create an associated issue if required.
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
sys.exit(salt_call())
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 443, in salt_call
client.run()
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/call.py", line 50, in run 
caller.run()
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 95, in run 
ret = self.call()
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 202, in call …

Add missing verify option for unwrap request

---

.github/workflows/docs-deploy.yml

Deploys built docs to GH pages on pushes to the master branch.
This is for testing and getting at least basic docs builds out, but could be integrated into the central workflow later.
The released docs are not versioned currently, only the latest ones are published.
Versioning support would require either (better):
* Rebuilding docs for all versions when a new release is made
* Version selector support in `furo`: https://github.com/pradyunsg/furo/pull/500
or (more basic):
* Using the `gh-pages` branch instead of Actions, `peaceiris/actions-gh-pages` to be able to deploy to subdirectories and using the tag/branch name as the directory name. The implementation via actions/deploy-pages always replaces the directory root.
Fixes: …

Publish latest docs to GH pages

---

.copier-answers.yml
CHANGELOG.md
README.md
changelog/10.fixed.md
changelog/11.fixed.md
changelog/12.fixed.md
changelog/13.fixed.md
changelog/14.fixed.md
changelog/15.fixed.md
changelog/16.added.md
changelog/17.added.md
changelog/18.added.md
changelog/19.added.md
changelog/20.added.md
changelog/21.added.md
changelog/22.fixed.md
changelog/23.added.md
changelog/26.added.md
changelog/30.changed.md
changelog/30.deprecated.md
changelog/34.fixed.md
pyproject.toml

* Include GitHub Pages URL as docs link
* Prepare first release
We have some (interim) rendered hosted docs now, so nothing prevents a `v1.0.0` release anymore.
Wanted to get this out soon to have an initial release that's mostly the same as was previously found in Salt (the modules have already been removed from the `master` branch). From here on, we will have more freedom to work on new features as well.
Ref: https://github.com/salt-extensions/saltext-vault/issues/37
Yes

Release v1.0.0

---

changelog/45.fixed.md
changelog/46.added.md
changelog/47.added.md
changelog/48.added.md
changelog/49.added.md
src/saltext/vault/utils/vault/cache.py
src/saltext/vault/utils/vault/client.py
src/saltext/vault/utils/vault/exceptions.py
src/saltext/vault/utils/vault/factory.py
src/saltext/vault/utils/vault/helpers.py
src/saltext/vault/utils/vault/kv.py
src/saltext/vault/utils/vault/leases.py
tests/functional/modules/test_vault.py
tests/integration/modules/test_vault.py
tests/integration/runners/test_vault.py
tests/unit/utils/vault/conftest.py
tests/unit/utils/vault/test_cache.py
tests/unit/utils/vault/test_factory.py
tests/unit/utils/vault/test_leases.py

* Fixes a crash when renewing/revoking leases that have been revoked on the Vault server early
* Allows to set default values for `revocation_delay`, `min_ttl`, and `renew_increment` on a lease when it is created.
* Allows to add metadata to a lease when it is created.
* Adds a LeaseStore method for listing cached leases matching a pattern.
* Some minor optimizations
With this, the utility module is mostly on par with the one I am using at the moment and most foundations are there for adding some more modules (like `vault_db`).
Fixes: https://github.com/salt-extensions/saltext-vault/issues/45
Fixes: https://github.com/salt-extensions/saltext-vault/issues/46
Fixes: https://github.com/salt-extensions/saltext-vault/issues/47
Fixes: https://github.com/salt-extensions/saltext-vault/issues/48 …

Lease handling improvements

---

.copier-answers.yml
changelog/70.removed.md
noxfile.py
pyproject.toml

Drops support for EOL Salt releases from the 3005 branch.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/70
Yes

Require Salt 3006

---

changelog/58.added.md
docs/index.rst
docs/ref/modules/index.rst
docs/ref/modules/saltext.vault.modules.vault_pki.rst
docs/ref/states/index.rst
docs/ref/states/saltext.vault.states.vault_pki.rst
docs/ref/utils/index.rst
docs/ref/utils/saltext.vault.utils.vault.pki.rst
pyproject.toml
src/saltext/vault/modules/vault_pki.py
src/saltext/vault/states/vault_pki.py
src/saltext/vault/utils/vault/client.py
src/saltext/vault/utils/vault/helpers.py
src/saltext/vault/utils/vault/kv.py
src/saltext/vault/utils/vault/pki.py
tests/functional/modules/test_vault_pki.py
tests/functional/states/test_vault_pki.py
tests/support/vault.py
tests/unit/modules/test_vault_pki.py
tests/unit/utils/vault/test_helpers.py
tests/unit/utils/vault/test_kv.py
tests/unit/utils/vault/test_pki.py

Add execution and state modules for managing and using Vault's PKI secret store.
Currently the following states are added:
- `certificate_managed` - Used to manage and renew certificates issued by Vault. Pretty much replicate the `x509.certificate_managed` module.
- `role_managed` - Used to manage PKI roles in Vault and keep them according to the state.
- `role_absent` - Used to ensure PKI role is absent from Vault.
In terms of execution module, there are several modules providing possibility to manage issuers, roles, certificates, keys.
Some updates in utils which will provide helpers for PKI modules functionality. 
Fixes: https://github.com/salt-extensions/saltext-vault/issues/56
Remove this section if not relevant
Remove this section if not relevant
**[NOTICE] Bug fixes or features …

Add `vault_pki` modules

---

changelog/61.added.md
changelog/62.added.md
docs/ref/states/index.rst
docs/ref/states/saltext.vault.states.vault_secret.rst
src/saltext/vault/modules/vault.py
src/saltext/vault/states/vault_db.py
src/saltext/vault/states/vault_secret.py
src/saltext/vault/utils/vault/__init__.py
src/saltext/vault/utils/vault/kv.py
src/saltext/vault/wrapper/vault.py
tests/functional/modules/test_vault.py
tests/functional/states/test_vault_secret.py
tests/integration/wrapper/test_vault.py
tests/unit/modules/test_vault.py
tests/unit/utils/vault/test_kv.py

* Adds support for reading specific versions of KV v2 secrets
* Adds support for restoring secret versions on KV v2
* Adds support for deleting/destroying all versions of secrets on KV v2
* Adds support for destroying the latest version without knowing its number on KV v2
* Adds support for completely wiping the metadata of a secret path on KV v2
* Adds state module for statefully managing secrets
Fixes: https://github.com/salt-extensions/saltext-vault/issues/61
Fixes: https://github.com/salt-extensions/saltext-vault/issues/62
Mostly ignorant about KV v2 versions.
More specific handling of KV v2 versions possible.
Yes

Secret (version) handling improvements

---

changelog/58.added.md
docs/index.rst
docs/ref/modules/index.rst
docs/ref/modules/saltext.vault.modules.vault_ssh.rst
docs/ref/states/index.rst
docs/ref/states/saltext.vault.states.vault_ssh.rst
docs/ref/wrapper/index.rst
docs/ref/wrapper/saltext.vault.wrapper.vault_ssh.rst
src/saltext/vault/modules/vault.py
src/saltext/vault/modules/vault_pki.py
src/saltext/vault/modules/vault_ssh.py
src/saltext/vault/states/vault.py
src/saltext/vault/states/vault_pki.py
src/saltext/vault/states/vault_ssh.py
src/saltext/vault/utils/vault/helpers.py
src/saltext/vault/wrapper/vault_pki.py
src/saltext/vault/wrapper/vault_ssh.py
tests/conftest.py
tests/functional/modules/test_vault_ssh.py
tests/functional/states/test_vault_ssh.py
tests/integration/files/vault/policies/ssh_admin.hcl
tests/integration/wrapper/test_vault_ssh.py
tests/support/vault.py

Adds execution, state and wrapper modules for the SSH secret backend.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/58
Yes

Add `vault_ssh` modules

---

changelog/85.fixed.md
src/saltext/vault/runners/vault.py

`vault.unseal` runner will now use unauthenticated query to unseal Vault
Fixes: 85
`vault.unseal` runner was trying to authenticate with Vault before unseal it.
`vault.unseal` runner will not do any authentication with Vault.
Yes

Make sure vault.unseal runner is unauthenticated

---

changelog/95.fixed.md
src/saltext/vault/utils/vault/factory.py
tests/unit/pillar/test_vault.py
tests/unit/runners/vault/test_vault.py
tests/unit/utils/vault/conftest.py
tests/unit/utils/vault/test_api.py
tests/unit/utils/vault/test_auth.py
tests/unit/utils/vault/test_cache.py
tests/unit/utils/vault/test_client.py
tests/unit/utils/vault/test_factory.py
tests/unit/utils/vault/test_helpers.py
tests/unit/utils/vault/test_kv.py
tests/unit/utils/vault/test_leases.py

Ensures the unwrap client uses client config if available. Also cleans up unnecessary Pylint pragmas in a second commit.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/95
When unwrapping authentication credentials without having a preexisting cached configuration, the unwrap requests would not respect the `vault:client` configuration.
Works as expected.
Yes

Ensure unwrap client uses client config if available

---

changelog/99.fixed.md
src/saltext/vault/runners/vault.py
tests/integration/runners/conftest.py
tests/integration/runners/test_vault.py
tests/integration/runners/test_vault_master_cluster.py
tests/unit/runners/vault/test_vault.py

Fix compatibility with master cluster mode
Fixes: https://github.com/salt-extensions/saltext-vault/issues/99
Crash because the `pki_dir` does not contain the minion's key, it's in `cluster_pki_dir`.
Works.
Yes

Fix compatibility with master cluster mode

---

docs/ref/configuration.md

Fix documentation
Fixes:
`auth:token` makes sense only when `auth:method` is set to `token`. I believe `approle` here is a c-n-p error.
Grammarly suggests that the word should be spelt `significance` in this case.
No
Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.
See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

Fix typo and spelling

---

changelog/+listcrash.fixed.md
changelog/106.added.md
docs/ref/configuration.md
docs/topics/templating.md
src/saltext/vault/runners/vault.py
src/saltext/vault/utils/vault/helpers.py
tests/integration/files/vault/policies/salt_minion.hcl
tests/integration/runners/test_vault.py
tests/unit/runners/vault/test_vault.py

* Fixes a crash when accessing out-of-bounds list items in templates
* Implements the workaround for composite values in metadata described in the linked issue/discussion
Fixes: https://github.com/salt-extensions/saltext-vault/issues/106
Ref: https://github.com/salt-extensions/saltext-vault/discussions/104
* No workable path to multiple roles per minion in templated policies
* Hard crash when accessing out-of-bounds list items
* Provides a somewhat workable path to multiple roles per minion in templated policies
* Accessing out-of-bounds list items is treated like accessing undefined keys (prints a warning)
Yes

Create separate metadata entries for composite values

---

changelog/111.fixed.md
src/saltext/vault/utils/vault/api.py
tests/functional/utils/test_vault_api.py

Catches `HTTP 404` returned by the Vault server when listing an empty AppRole mount.
This fixes the `vault.sync_approles`/`vault.list_approles` runner functions when no minion has been invoked yet.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/111
Crash.
Works.
**[NOTICE] Bug fixes or new features require tests.**
Yes

Don't crash when listing empty AppRole mount

---

CHANGELOG.md
changelog/111.fixed.md

Reverts salt-extensions/saltext-vault#119
The release failed because `setuptools` release 77 introduced Core Metadata version 2.4, which is incompatible with the `twine` version used in the publish action.

Revert "Release v1.3.1"

---

.github/workflows/test-action.yml
changelog/123.fixed.md
src/saltext/vault/states/vault_pki.py
src/saltext/vault/utils/vault/pki.py
tests/functional/beacons/test_vault_lease.py
tests/functional/modules/test_vault.py
tests/functional/modules/test_vault_db.py
tests/functional/modules/test_vault_pki.py
tests/functional/modules/test_vault_ssh.py
tests/functional/states/test_vault_db.py
tests/functional/states/test_vault_pki.py
tests/functional/states/test_vault_secret.py
tests/functional/states/test_vault_ssh.py
tests/functional/utils/test_vault_api.py
tests/integration/modules/test_vault.py
tests/integration/runners/test_vault.py
tests/integration/runners/test_vault_master_cluster.py
tests/integration/sdb/test_vault.py
tests/integration/states/test_vault_db.py
tests/integration/wrapper/test_vault.py
tests/integration/wrapper/test_vault_db.py
tests/integration/wrapper/test_vault_pki.py
tests/integration/wrapper/test_vault_ssh.py
tests/unit/utils/vault/test_pki.py

Fixes an issue that includes self-signed root certificates when writing CA chains.
This resulted in non-idempotency of `vault_pki.certificate_managed`.
Fixes: https://github.com/salt-extensions/saltext-vault/issues/123
Includes self-signed root certificates in CA chains.
Always reports changes.
Excludes self-signed root certificates in CA chains.
Idempotent.
**[NOTICE] Bug fixes or new features require tests.**
No

Don't include self-signed certificates in ca_chain
